### ISSUE TITLE
SME Review - Workshop outline

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/MCW-Securing-the-IoT-end-to-end#1]
Please place all feedback to the workshop outline in this issue by continuing the conversation below.

**Comment by AltaOhms** [comment]
Hi there,

When talking about IoT Security, I recommend highlighting the following: 

- Azure Security Center for IoT
- Azure IoT Hub (Which Lab Does..)
- DPS - This you can cover x.509 certs and TPM, OTA and  
- IoT Edge 
- Azure Sphere
- Azure Sentinel

Plus, there are a lot of resources we can be pointing to talking about IoT Security. When is this suppose to go live? Thanks!

**Comment by AltaOhms** [comment]
Content & Resources:

- https://www.microsoft.com/en-us/research/wp-content/uploads/2017/03/SevenPropertiesofHighlySecureDevices.pdf
- https://azure.microsoft.com/en-us/overview/iot/security/
- https://docs.microsoft.com/en-us/azure/iot-fundamentals/iot-security-best-practices

**Comment by swan-am-i** [comment]
Securing the IoT Arch is coming.. some of the things that will be added include:
Preliminary thoughts:
1) On device side, how the certs/keys are stored.  What services run and what ports are required to be open.  How OS and application updates are handled
2) On transport,  TLS or MTLS version supported
3) On cloud whitelisting IP addresses, network peering (if using express route)
4) Encryption on data rest, if stored in say Blob storage.  In some cases use of customer keys for encryption

**Comment by givenscj** [comment]
Added all the appropriate resource links to the WDS files and integrated some with the customer objections.
