### ISSUE TITLE
tpm var is emtpy

### ISSUE THREAD

**Issue by pietrobr** [solliancenet/MCW-Securing-the-IoT-end-to-end#3]
Hi I'm following the HOL, 

after running

tpm=$(sudo find /sys -name dev -print | fgrep tpm | sed 's/.\{4\}$//')

if I print out the variable , like echo $tpm, I get an empty line, I'm not sure if it's ok, but then after 

sudo systemctl status iotedge the service failed to start, so runing

sudo journalctl -u iotedge I get those errors

Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: 2019-06-12T09:12:51Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: 2019-06-12T09:12:51Z [ERR!] -         caused by: HSM API returned an invalid null response
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: Error: Time:Wed Jun 12 09:12:51 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_usermode
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: Error: Time:Wed Jun 12 09:12:51 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_comm_cre
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: Error: Time:Wed Jun 12 09:12:51 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Co
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: 2019-06-12T09:12:51Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:272) Failur
Jun 12 09:12:51 oilwells-edgevm-pietro iotedged[3333]: 2019-06-12T09:12:51Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_client_tpm_create:305) Failur
Jun 12 09:12:51 oilwells-edgevm-pietro systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE

**Comment by givenscj** [comment]
Hi there,

All these labs are VERY preliminary (as is all the Azure IoT agent source code). Please don't run through them as part of your outline review, they are all subject to change. However, feel free to comment on the high-level theory of the labs though!

Chris

NOTE:  This is by design as you do not have a hardware TPM and the default agent code is compiled to support hardware TPM.
